config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root 'articles#index'
   resources :articles do
       resources :comments
   end
  get 'welcome/index'

  # delete '/articles/:id' {:action=>"destroy", :controller=>"articles/index"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title,:text, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# ensure admin for other actions
before_action :authenticate_user!

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    puts "inside me"
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to root_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text, :User)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  # def show
  #   @comment = Comment.find(params[:id])
  # end
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :User)
    end
    end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
  <style>
      html, body {
      min-height: 100%;
      }
      body, div, form, input, label { 
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 13px;
      color: #666;
      line-height: 18px;
      }
      legend { 
      color: #fff;
      background-color: #095484;
      padding: 3px 5px;
      font-size: 20px;
      }
      h1 {
    position: absolute;
    margin: 6px;
    font-size: 22px;
    z-index: 2;
   
      }
      .testbox {
      display: flex;
      justify-content: center;
      align-items: center;
      height: inherit;
      padding: 20px;
      }
      .myform {
         width: 92%;
    padding: 20px;
    border-radius: 6px;
    background: #fff;
    box-shadow: 0 0 2px 0 #095484;
}


      }
     
      input {
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 3px;
      }
      input {
      width: calc(100% - 10px);
      padding: 5px;
      width: 96%;
      }
      select {
      width: 100%;
      padding: 7px 0;
      background: transparent;
      }
      .text-area{
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 3px;
      width: 97%;
      }
      input[type="date"] {
      padding: 4px 5px;
      }
      .item:hover p, .item:hover i, .question:hover p, .question label:hover, input:hover::placeholder {
      color:#095484;
      }
      .item input:hover {
      border: 1px solid transparent;
      box-shadow: 0 0 6px 0 #095484;
      color:#095484;
      }
      .item {
      position: relative;
      margin: 10px 0;
      }
      .item span {
      color: red;
      }
      input[type="date"]::-webkit-inner-spin-button {
      display: none;
      }
      .item i, input[type="date"]::-webkit-calendar-picker-indicator {
      position: absolute;
      font-size: 20px;
      color: #095484;
      }
      .item i {
      right: 2%;
      top: 30px;
      z-index: 1;
      }
      [type="date"]::-webkit-calendar-picker-indicator {
      right: 1%;
      z-index: 2;
      opacity: 0;
      cursor: pointer;
      }
      .question span {
      margin-left: 30px;
      }
      .btn-block {
      margin-top: 10px;
      text-align: center;
      }
      button {
      width: 150px;
      padding: 10px;
      border: none;
      border-radius: 5px; 
      background: #095484;
      font-size: 16px;
      color: #fff;
      cursor: pointer;
      }
      button:hover {
      background: #4286f4;
      }
      @media (min-width: 568px) {
      .name-item, .city-item {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      }
      .name-item input, .city-item input,.name-item div {
      width: calc(50% - 20px);
      }
      .name-item div input {
      width:97%;}
      .name-item div label {
      display:block;
      padding-bottom:5px;
      }
      }
    </style>

<div class="myform">
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text,:class=>"text-area" %>
  </p>
  <p style ="display: none;">
    <%= form.text_field :User, value: current_user.id %>
  </p>
  <p>
    <%= form.submit :class=>"create-btn"%>
  </p>
 

<% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= render 'form' %>
 
 <p class="btn-add-new box noprint"><strong><%= link_to 'Back', articles_path %></strong></p>

app/views/articles/index.html.erb
<style>

</style>
<h1>Listing Articles</h1>

   <!-- Article -->
     <% @articles.each do |article| %>

            <div class="article">
                <h2><span><a href="#"><%= article.title %></a></span></h2>
                <p class="info noprint">
                    <span class="date"><%= time_ago_in_words(article.updated_at) %></span><span class="noscreen"> ago</span>
                 <!--   <span class="cat"><a href="#">Category</a></span><span class="noscreen">,</span>
                    <span class="user"><a href="#">My name</a></span><span class="noscreen">,</span>
                    <span class="comments"><a href="#">Comments</a></span> -->
                </p>

                <p><%= article.text %></p>
                <p class="btn-more box noprint"><strong><%= link_to 'Show', article_path(article) %></strong></p>
                <br/>
                <% if article.User == current_user.id %>
                  
                
                    <p class="btn-more box noprint"><strong><%= link_to 'Edit', edit_article_path(article) %></strong></p>
                    <br/>
                <p class="btn-more box noprint"><strong><%= button_to "Destroy",articles_path,  method: :destroy, data: { confirm: "Are you sure?" }, disable_with: "Processing...",:class=>"btn_cls"  %></strong></p>
<% end %>
            </div> <!-- /article -->

            <hr class="noscreen" />
             <% end %>
 <!--
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= button_to "Destroy", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class:"btn_cls" %></td>
    </tr>
  <% end %>
</table>
-->
<br/>
<br/>
<!-- <%= link_to 'My Blog', controller: 'articles' %>-->
<p class="btn-add-new box noprint">
<strong>
<%= link_to 'Add New', new_article_path %>
</strong>
</p>

app/views/articles/new.html.erb
<h1>New Article</h1>
 
<%= render 'form' %>
 
<p class="btn-add-new box noprint"><strong><%= link_to 'Back', articles_path %></strong></p>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
               

<h2>Comments</h2>
<%= render @article.comments %>
<div style="margin-top :20%;">
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 </div>
 <div>
<p class="btn-add-new box noprint"><strong><%= link_to 'Edit', edit_article_path(@article) %></strong></p>
<p class="btn-add-new box noprint"><strong><%= link_to 'Back', articles_path %></strong></p>
</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

 <br/>
  <% if comment.User == current_user.id %>
<%= button_to "Destroy Comment", [comment.article, comment],
               method: :delete,
               data: { confirm: "Are you sure?" },:class=>"destroy-btn" %>
               <% end%>
   

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
<p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body,:class =>"text-area" %>
  </p>
  <p style ="display: none;">
    <%= form.text_field :User, value: current_user.id %>
  </p>
  <p>
    <%= form.submit :class=>"create-btn" %>
  </p>
<% end %>

app/views/comments/show1.html.erb
<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= @comment.body %>
</p>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <%# <%= javascript_include_tag :defaults %>
<%# <%= csrf_meta_tag %>
  </head>
<style>


</style>
  <body id="www-url-cz">

<!-- Main -->
<div id="main" class="box">

    <!-- Header -->
    <div id="header">


    </div> <!-- /header -->

     <!-- Main menu (tabs) -->
     <div id="tabs">

            <h3 >Blog Application </h3>
             <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
   <br/>
  <% end %>
 
            <ul class="box">
              <% if user_signed_in? %>
                <li><a href="#">Home<span class="tab-l"></span><span class="tab-r"></span></a></li>
               <li><%= link_to "Blogs" , articles_path %> </li>
             
  <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
  <li><%= button_to "Logout", destroy_user_session_path, method: :delete, :class=>"lgt-btn" %></li>
<% else %>
 <li> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
 <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
<% end %>
            </ul>

        <hr class="noscreen" />
     </div> <!-- /tabs -->

    <!-- Page (2 columns) -->
    <div id="page" class="box">
    <div id="page-in" class="box">

        <div id="strip" class="box noprint">

            <!-- RSS feeds -->
            
            <hr class="noscreen" />

            <!-- Breadcrumbs -->
            <%# <p id="breadcrumbs">You are here: <a href="#">Home</a> &gt; <a href="#">Category</a> &gt;  <strong>Page</strong></p> %>
            <%# <hr class="noscreen" /> %>
            
        </div> <!-- /strip -->

        <!-- Content -->
        <div id="content">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
         <%= yield %>

            
        </div> <!-- /content -->

        <!-- Right column -->
        <div id="col" class="noprint">
            <div id="col-in">

                <!-- About Me -->
                <h3><span><a href="#">About Me</a></span></h3>

                <div id="about-me">
                  <% if user_signed_in? %>
<strong><%= current_user.email %></strong>.
   <br/>
  <% end %>

                    <a href="#">Profile on MySpace</a></p>
                </div> <!-- /about-me -->

                <hr class="noscreen" />

                <%# <!-- Category -->
                <h3 ><span>Category</span></h3>

                <ul id="category">
                    <li id="category-active"><a href="#">Selected category</a></li> <!-- Active -->
                    <li><a href="#">Category</a></li>
                    <li><a href="#">Category</a></li>
                    <li><a href="#">Category</a></li>
                    <li><a href="#">Category</a></li>
                </ul>

                <hr class="noscreen" /> %>

                <!-- Archive -->
                <h3><span>Archive</span></h3>

                <ul id="archive">
                   <li  id="archive-active"><a href="#">January 2022</a></li>
                    <li><a href="#">December 2021</a></li>
                    <li><a href="#">November 2021</a></li>
                    <li><a href="#">October 2021</a></li>
                    <li><a href="#">September 2021</a></li>
                   
                </ul>

                <hr class="noscreen" />


                <hr class="noscreen" />
            
            </div> <!-- /col-in -->
        </div> <!-- /col -->

    </div> <!-- /page-in -->
    </div> <!-- /page -->

    <!-- Footer -->
    <div id="footer">
        <div id="top" class="noprint"><p><span class="noscreen">Back on top</span> <a href="#header" title="Back on top ^">^<span></span></a></p></div>
      
        
        <p id="createdby">created by <a href="#"></a> <!-- DON´T REMOVE, PLEASE! --></p>
        <p id="copyright">&copy; 2007 <a href="mailto:my@mail.com">My Name</a></p>
    </div> <!-- /footer -->

</div> <!-- /main -->

</body>
 
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>